# Basic array operation

In [1]:
import numpy as np

In [2]:
a = np.array([5,6,7])

In [3]:
a[0]

5

In [5]:
a.ndim

1

In [6]:
b = np.array([[1,2],[3,4],[5,6]])

In [7]:
b.ndim

2

In [8]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
b.itemsize

4

In [10]:
c =  np.array([[1,2],[3,4],[5,6]],dtype = np.float64)

In [11]:
c.itemsize

8

In [12]:
c

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [13]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
# size define the number of element in the array
a.size

3

In [21]:
b.size

6

In [22]:
c.size

6

In [25]:
e = np.zeros([3,3])
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
e.ndim

2

In [27]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [31]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
b.shape

(3, 2)

In [34]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [37]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
b.min()

1

In [39]:
b.max()

6

In [40]:
b.sum()

21

In [41]:
b.sum(axis=0)

array([ 9, 12])

In [42]:
b.sum(axis=1)

array([ 3,  7, 11])

In [43]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [44]:
a = np.array([[1,2],[3,4]])

In [45]:
b = np.array([[5,6],[7,8]])

In [46]:
a

array([[1, 2],
       [3, 4]])

In [47]:
b

array([[5, 6],
       [7, 8]])

In [48]:
a+b

array([[ 6,  8],
       [10, 12]])

In [49]:
a-b

array([[-4, -4],
       [-4, -4]])

In [50]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [51]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [52]:
a = np.array([1,2,3,4,5,6])

In [53]:
a[0:3]

array([1, 2, 3])

In [54]:
b

array([[5, 6],
       [7, 8]])

# Slicing

In [55]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
b[1,2]

6

In [58]:
b[0:2,2]

array([3, 6])

In [60]:
b[-2]

array([4, 5, 6])

In [61]:
b[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [62]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
for row in b:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [64]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6


# Stacking

In [66]:
a = np.arange(6).reshape([3,2])
b = np.arange(6,12).reshape([3,2])

In [67]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [68]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [71]:
c = np.arange(30).reshape([2,15])

In [72]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [74]:
result = np.hsplit(c,3)

In [75]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [76]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [77]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [78]:
result2 = np.vsplit(c,2)

In [79]:
result2[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [80]:
result2[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [81]:
a = np.arange(12).reshape([3,4])

In [82]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
b = a>4

In [84]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [87]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [88]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [89]:
np.savetxt('test.txt',a)

In [90]:
np.loadtxt('test.txt')

array([[ 0.,  1.,  2.,  3.],
       [ 4., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [91]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [92]:
a = np.arange(12).reshape([3,4])

In [93]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [96]:
for cell in a.flat:
    print(cell)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [97]:
for x in np.nditer(a,order='c'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [98]:
for x in np.nditer(a,order='f'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [99]:
for x in np.nditer(a,order='f',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [100]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [101]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])